name: Build .NET Desktop App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Specify your required .NET SDK version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Publish output
        run: dotnet publish --configuration Release --output ./output
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: ./output
